const sports=['All','Football','Basketball','Soccer','Baseball','Hockey','Racing','Golf','Tennis','Boxing','Other'];
const seed=[['Touchdown Target','Football','🏈','Hit the end-zone target','target'],['Field Goal Flick','Football','🏈','Kick through the uprights','target'],['QB Accuracy','Football','🎯','Hit moving receivers','target'],['End Zone Rush','Football','🏃','Dodge defenders','dodge'],['Football Sprint','Football','⚡','Survive the sprint','dodge'],['Hoop Shot','Basketball','🏀','Sink the shot','target'],['3 Point Challenge','Basketball','🎯','Score from deep','target'],['Dunk Dash','Basketball','🔥','Time your run','dodge'],['Court Hustle','Basketball','🏀','Avoid defenders','dodge'],['Free Throw Pro','Basketball','🏀','Perfect your throws','target'],['Penalty Shootout','Soccer','⚽','Beat the keeper','target'],['Goal Rush','Soccer','🥅','Score fast','target'],['Dribble Dash','Soccer','⚽','Avoid tackles','dodge'],['Corner Kick','Soccer','🎯','Hit the corner','target'],['Golden Boot','Soccer','👟','Rack up goals','target'],['Home Run Derby','Baseball','⚾','Smash pitches','baseball'],['Batting Practice','Baseball','⚾','React to pitches','baseball'],['Fastball Challenge','Baseball','🔥','Time your swing','baseball'],['Base Runner','Baseball','🏃','Steal bases','dodge'],['Grand Slam','Baseball','💥','Find the sweet spot','baseball'],['Hockey Slapshot','Hockey','🏒','Beat the goalie','target'],['Ice Breaker','Hockey','🧊','Score under pressure','target'],['Puck Accuracy','Hockey','🎯','Hit targets','target'],['Goalie Hero','Hockey','🥅','Save shots','target'],['Rink Rush','Hockey','🏒','Race across the ice','dodge'],['Street Racer','Racing','🏎️','Dodge traffic','dodge'],['Formula Sprint','Racing','🏁','Survive the track','dodge'],['Drift Master','Racing','💨','Stay on course','dodge'],['Turbo Traffic','Racing','🚘','Weave through traffic','dodge'],['Drag Race','Racing','🚦','Launch perfectly','dodge'],['Mini Golf','Golf','⛳','Sink the putt','target'],['Golf Target','Golf','🎯','Land near the flag','target'],['Long Drive','Golf','🏌️','Max your drive','target'],['Putt Perfect','Golf','⛳','Read the green','target'],['Fairway Challenge','Golf','🌳','Keep it straight','target'],['Tennis Serve','Tennis','🎾','Serve the target','target'],['Ace Attack','Tennis','🎾','Serve an ace','target'],['Rally Master','Tennis','⚡','Keep the rally alive','target'],['Court Target','Tennis','🎯','Hit the corners','target'],['Tennis Dash','Tennis','🎾','Reach every shot','dodge'],['Boxing Punch','Boxing','🥊','Punch targets','boxing'],['Heavyweight','Boxing','🥊','Land combos','boxing'],['Speed Bag','Boxing','⚡','Tap targets','boxing'],['Knockout Round','Boxing','💥','Find the opening','boxing'],['Ring Rush','Boxing','🥊','Survive the round','dodge'],['Skate Sprint','Other','⛸️','Race to the finish','dodge'],['Archery Ace','Other','🏹','Hit the bullseye','target'],['Bowling Blitz','Other','🎳','Knock down pins','target'],['Volleyball Serve','Other','🏐','Serve into the target','target'],['Track Sprint','Other','🏃','Sprint to victory','dodge']];
const games=[...seed,...Array.from({length:60},(_,i)=>{let s=sports[1+i%10];let icons={Football:'🏈',Basketball:'🏀',Soccer:'⚽',Baseball:'⚾',Hockey:'🏒',Racing:'🏎️',Golf:'⛳',Tennis:'🎾',Boxing:'🥊',Other:'🏆'};return [`${s} Challenge ${i+1}`,s,icons[s],'A fresh arcade challenge','target']])];
let fav=JSON.parse(localStorage.fav||'[]'), active='All', xp=Number(localStorage.xp||0), best=Number(localStorage.best||0), player=localStorage.player||'Rookie';
const $=x=>document.querySelector(x);$('#playerName').textContent=player;
function chips(){ $('#chips').innerHTML=sports.map(s=>`<button class="chip ${s===active?'active':''}" data-s="${s}">${s}</button>`).join('');document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{active=b.dataset.s;chips();render()}) }
function render(){let q=$('#search').value.toLowerCase();let list=games.filter(g=>(active==='All'||g[1]===active)&&g.join(' ').toLowerCase().includes(q));$('#grid').innerHTML=list.map((g,i)=>`<article class="card"><div class="pic">${g[2]}</div><div class="body"><h3>${g[0]}</h3><p>${g[3]} • ${g[1]}</p><button class="play" data-i="${games.indexOf(g)}">PLAY ▶</button></div></article>`).join('');$('#statGames').textContent=games.length+'+';$('#heroGames').textContent=games.length+'+'}
$('#search').oninput=render;chips();render();
$('#theme').onclick=()=>document.body.classList.toggle('light');
$('#nameBtn').onclick=()=>{let n=prompt('Enter your arcade name:',player);if(n){player=n.slice(0,20);localStorage.player=player;$('#playerName').textContent=player}};
function updateStats(){let level=Math.floor(xp/100)+1;$('#statXP').textContent=xp;$('#statBest').textContent=best;$('#level').textContent=level;$('#xpText').textContent=xp+' XP';$('#xpbar').style.width=(xp%100)+'%'}updateStats();
const modal=$('#modal');$('#close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
$('#grid').onclick=e=>{let b=e.target.closest('.play');if(b)start(games[Number(b.dataset.i)])};
function close(){modal.classList.add('hidden');$('#game').innerHTML='';if(window.gaf)cancelAnimationFrame(window.gaf);if(window.gcleanup)window.gcleanup()}
function start(g){close();modal.classList.remove('hidden');$('#game').innerHTML=`<h2 class="gameTitle">${g[2]} ${g[0]}</h2><p class="gameSub">${g[3]} • Click/tap the target. Use A/D or ←/→ for dodge games.</p><canvas width="760" height="430"></canvas><div class="gameButtons"><button id="restart">↻ Restart</button></div>`;let c=$('#game canvas'),x=c.getContext('2d'),W=c.width,H=c.height,t=0,score=0,over=false,px=W/2,target={x:W/2,y:110,r:35},keys={};function reset(){t=0;score=0;over=false;px=W/2;target={x:W/2,y:110,r:35}}$('#restart').onclick=reset;function kd(e){keys[e.key.toLowerCase()]=1}function ku(e){keys[e.key.toLowerCase()]=0}addEventListener('keydown',kd);addEventListener('keyup',ku);window.gcleanup=()=>{removeEventListener('keydown',kd);removeEventListener('keyup',ku)};c.onclick=e=>{if(over)return;let r=c.getBoundingClientRect(),mx=(e.clientX-r.left)*W/r.width,my=(e.clientY-r.top)*H/r.height;if(Math.hypot(mx-target.x,my-target.y)<target.r+10){score++;xp+=10;localStorage.xp=xp;best=Math.max(best,score);localStorage.best=best;updateStats();target.x=55+Math.random()*(W-110);target.y=75+Math.random()*(H-180);target.r=Math.max(17,target.r-.7)}};function draw(){x.fillStyle='#081018';x.fillRect(0,0,W,H);x.strokeStyle='#203244';for(let a=20;a<W;a+=50){x.beginPath();x.moveTo(a,0);x.lineTo(a,H);x.stroke()}for(let a=20;a<H;a+=50){x.beginPath();x.moveTo(0,a);x.lineTo(W,a);x.stroke()}x.fillStyle='white';x.font='800 19px Arial';x.fillText('SCORE '+score,20,32);if(g[4]==='dodge'){px+=(keys.d||keys.arrowright?6:0)-(keys.a||keys.arrowleft?6:0);px=Math.max(25,Math.min(W-25,px));for(let i=0;i<6;i++){let yy=(t*(2+i*.35)+i*90)%470-30;let xx=55+((i*137)%650);x.fillStyle=['#3ee58e','#5ca8ff','#ff5c68','#ffd15a'][i%4];x.fillRect(xx-15,yy,30,46)}x.fillStyle='white';x.beginPath();x.arc(px,H-55,17,0,7);x.fill();if(t>900)over=true}else if(g[4]==='boxing'){x.fillStyle='#ff5c68';x.beginPath();x.arc(target.x,target.y,target.r,0,7);x.fill();x.fillStyle='white';x.textAlign='center';x.fillText('HIT',target.x,target.y+6);x.textAlign='left';if(t%45===0){target.x=70+Math.random()*(W-140);target.y=80+Math.random()*(H-180)}}else{x.fillStyle='#3ee58e';x.beginPath();x.arc(target.x,target.y,target.r,0,7);x.fill();x.fillStyle='#06110b';x.textAlign='center';x.fillText('TARGET',target.x,target.y+5);x.textAlign='left'}if(over){x.fillStyle='white';x.textAlign='center';x.font='bold 48px Arial';x.fillText('FINISH!',W/2,H/2);x.textAlign='left'}t++;window.gaf=requestAnimationFrame(draw)}draw()}
